### ISSUE TITLE
Xcode 13.2.1 can't compile

### ISSUE THREAD

**Issue by romk1n** [Instabug/Instabug-Flutter#332] opened 2023-02-06 14:11 UTC
### Steps to Reproduce the Problem
use flutter 11.6.0

### Expected Behavior
complication works

### Actual Behavior

/Users/admin/.pub-cache/hosted/pub.dev/instabug_flutter-11.6.0/ios/Classes/Modules/InstabugApi.m:23:11: Definition of 'Instabug' must be imported from module 'Instabug' before it is required

**Comment by TheBuggedYRN** [comment] 2023-02-06 14:59
Hello @romk1n!
I think this is a duplicate of #324.
Please try the suggested solution and feel free to reopen if it didn't solve your issue.

**Closed by TheBuggedYRN** 2023-02-06 14:59 UTC

**Comment by romk1n** [comment] 2023-02-06 15:01
Will get back to you, we did try `git clean -ffdx` which would get rid of all the files in the repo, but perhaps the problem is ineed with pod cache..
